name: Full build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm --needed nodejs git clang cmake ninja shaderc vulkan-validation-layers vulkan-utility-libraries wayland wayland-protocols libxkbcommon glm libpng libjpeg-turbo libjxl libwebp libheif systemd-libs libdrm libdisplay-info mesa python
    - uses: actions/checkout@v3
    - run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
      env:
        CC: clang
        CXX: clang++
    - run: ninja -C build
