name: Full build

on: [push]

jobs:
  build:
    runs-on: arch-latest
    steps:
    - name: Install dependencies
      run: pacman -Syu --noconfirm && pacman -S --noconfirm --needed nodejs git clang meson shaderc vulkan-validation-layers wayland wayland-protocols libxkbcommon glm libpng libjpeg-turbo libjxl libwebp libheif systemd-libs libdrm libdisplay-info mesa
    - uses: actions/checkout@v3
    - name: Setup build
      run: meson setup build
      env:
        CC: clang
        CXX: clang++
    - name: Run build
      run: ninja -C build
