name: Full build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
    - name: Install dependencies
      run: |
        pacman-key --init
        pacman -Syu --noconfirm
        pacman -S --noconfirm --needed nodejs git clang cmake ninja shaderc vulkan-headers vulkan-validation-layers vulkan-utility-libraries wayland wayland-protocols libxkbcommon glm libpng libjpeg-turbo libjxl libwebp libheif systemd-libs libdrm libdisplay-info mesa python mold libtiff libraw openexr libsixel cairo librsvg libexif pugixml
    - uses: actions/checkout@v4
    - name: clang configure
      run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
      env:
        CC: clang
        CXX: clang++
    - name: clang build
      run: ninja -C build install
      env:
        DESTDIR: ${{ github.workspace }}/install
    - name: gcc configure
      run: cmake -G Ninja -B build-gcc -DCMAKE_BUILD_TYPE=Release -DBUILD_MCORE=1
      env:
        CC: gcc
        CXX: g++
    - name: gcc build
      run: ninja -C build-gcc
    - run: strip ${{ github.workspace }}/install/*
    - uses: actions/upload-artifact@v3
      with:
        path: install
