name: vv-only build

on: [push]

jobs:
  build-vv:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
    - name: Install dependencies
      run: |
        pacman-key --init
        pacman -Syu --noconfirm
        pacman -S --noconfirm --needed git clang cmake ninja mold python nodejs libpng libjpeg-turbo libjxl libwebp libheif libtiff libraw openexr libsixel cairo librsvg libexif pugixml lz4 lcms2
    - uses: actions/checkout@v4
    - name: configure
      run: cmake --preset=release -DBUILD_IV=OFF -DBUILD_TESTS=OFF
      env:
        CC: clang
        CXX: clang++
    - name: build
      run: ninja -C build-release
